<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ConfigTests</RootNamespace>
    <AssemblyName>ConfigTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../windows/Applet/AppletConfig.cs" />
  </ItemGroup>
</Project>
