#!/usr/bin/env bash
# Isolated staging stack for the admin-portal release (docker-compose.staging.yml).
#
#   ./scripts/staging.sh up       build and start (fresh database on first run)
#   ./scripts/staging.sh reset    wipe the staging database and start again
#   ./scripts/staging.sh status   containers and health
#   ./scripts/staging.sh logs     follow the staging app log
#   ./scripts/staging.sh down     stop and remove staging containers AND its volume
#
#   Technician console : http://localhost:18080
#   Admin portal       : http://localhost:18081
#   First admin        : development sign-in, object ID below, role Admin
#
# SAFETY: every compose call here uses `-p hda-staging` and its own env file, so
# it cannot touch the live `helpdeskanywhere` containers, network, volumes, image
# or ./audit. Never run plain `docker compose down` for staging.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

PROJECT=hda-staging
ENV_FILE="$repo_root/.env.staging"
BOOTSTRAP_OID="${STAGING_BOOTSTRAP_OID:-aaaaaaaa-0000-4000-8000-000000000001}"

if [[ ! -f "$ENV_FILE" ]]; then
  umask 077
  cat > "$ENV_FILE" <<ENV
# Generated by scripts/staging.sh — staging only, never production.
PUBLIC_HOST=localhost:18080
ADMIN_PUBLIC_HOST=localhost:18081
ADMIN_LOCAL_PORT=18081
POSTGRES_PASSWORD=$(openssl rand -hex 16)
ENTRA_TENANT_ID=unused-in-staging
ENTRA_CLIENT_ID=unused-in-staging
ENTRA_CLIENT_SECRET=unused-in-staging
# Required by compose interpolation for the (unused) ngrok profile.
NGROK_AUTHTOKEN=unused-in-staging
BOOTSTRAP_ADMIN_OIDS=$BOOTSTRAP_OID
TRANSCRIPT_RETENTION_DAYS=365
SESSION_RETENTION_DAYS=730
REPORT_TTL_MINUTES=15
ENV
fi

export HOST_UID="${HOST_UID:-$(id -u)}" HOST_GID="${HOST_GID:-$(id -g)}"
mkdir -p .staging-audit
compose=(docker compose -p "$PROJECT" --env-file "$ENV_FILE" -f docker-compose.yml -f docker-compose.staging.yml)

wait_healthy() {
  for _ in $(seq 1 90); do
    if curl -sf http://127.0.0.1:18080/healthz >/dev/null && curl -sf http://127.0.0.1:18081/healthz >/dev/null; then
      return 0
    fi
    sleep 1
  done
  echo "staging did not become healthy — ./scripts/staging.sh logs" >&2
  return 1
}

case "${1:-up}" in
  up)
    "${compose[@]}" build app
    "${compose[@]}" up -d db app
    wait_healthy
    echo
    echo "  Technician console : http://localhost:18080"
    echo "  Admin portal       : http://localhost:18081"
    echo "  First admin        : object ID $BOOTSTRAP_OID, role Admin (development sign-in)"
    ;;
  reset)
    "${compose[@]}" rm -sf app db >/dev/null
    docker volume rm "${PROJECT}_pgdata" >/dev/null 2>&1 || true
    rm -rf .staging-audit && mkdir -p .staging-audit
    exec "$0" up
    ;;
  status) "${compose[@]}" ps ;;
  logs)   "${compose[@]}" logs -f app ;;
  down)   "${compose[@]}" down -v ;;
  *) sed -n '2,15p' "$0"; exit 2 ;;
esac
