#!/usr/bin/env bash
# Cloud migration — Phase 3/5. Run this on the CURRENT (source) VM.
#
# Snapshots everything needed to recreate this Helpdesk Anywhere deployment on
# a new VM: non-secret config, .env (restricted perms preserved), audit logs,
# the generated Windows .exe, and a live-generated migration manifest. Does
# NOT touch the running application or any git state — read-only against the
# live deployment.
#
#   ./scripts/cloud-migration/backup-current-vm.sh
#
# Output:
#   ~/hda-migration/{config,data,audit,generated,docker,system,manifests,restore}/
#   ~/hda-migration-<timestamp>.tar.gz          (portable archive)
#   ~/hda-migration-<timestamp>.tar.gz.sha256   (its checksum)
#
# Secrets are never printed to the console and never included unredacted in
# any generated text file. .env is copied byte-for-byte (its values are
# needed to restore the deployment) but its permissions (600) are preserved,
# and nothing echoes its contents.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

if [[ ! -f docker-compose.yml || ! -f CLAUDE.md ]]; then
  echo "error: $repo_root does not look like the Helpdesk Anywhere repo root" >&2
  exit 1
fi

backup_root="${HDA_MIGRATION_DIR:-$HOME/hda-migration}"
timestamp="$(date -u +%Y%m%d-%H%M%S)"

echo "→ project: $repo_root"
echo "→ backup root: $backup_root"

for d in config data audit generated docker system manifests restore; do
  mkdir -p "$backup_root/$d"
done

# ---------------------------------------------------------------- config/
# .env is copied with its restrictive mode preserved. Never cat/echo it.
if [[ -f .env ]]; then
  install -m 600 .env "$backup_root/config/.env"
  echo "→ copied .env (permissions preserved, contents not shown)"
else
  echo "→ WARNING: .env not found — nothing to restore secrets from" >&2
fi
for f in .env.example Caddyfile docker-compose.yml docker-compose.local.yml docker-compose.caddy-local.yml; do
  [[ -f "$f" ]] && cp -f "$f" "$backup_root/config/$f"
done

# ---------------------------------------------------------------- audit/
# The only persistent application state (CLAUDE.md constraint #5). Session
# state itself is in-memory by design — nothing else to snapshot here.
if compgen -G "audit/*.jsonl" >/dev/null 2>&1; then
  cp -f audit/*.jsonl "$backup_root/audit/"
  echo "→ copied $(compgen -G "audit/*.jsonl" | wc -l) audit log file(s)"
else
  echo "→ no audit/*.jsonl files found"
fi

# ---------------------------------------------------------------- generated/
# The built applet. Rebuilding is cheap (build-windows.sh) but it must be
# re-baked with the NEW host's URL regardless, so this copy is a reference/
# hash record, not something restore-new-vm.sh will serve as-is.
if compgen -G "server/public/download/*.exe" >/dev/null 2>&1; then
  cp -f server/public/download/*.exe "$backup_root/generated/"
fi
if compgen -G "server/public/download/*.ps1" >/dev/null 2>&1; then
  cp -f server/public/download/*.ps1 "$backup_root/generated/"
fi
if compgen -G "$backup_root/generated/*" >/dev/null 2>&1; then
  (cd "$backup_root/generated" && sha256sum * > SHA256SUMS.generated 2>/dev/null || true)
  echo "→ copied generated download artifacts"
fi

# ---------------------------------------------------------------- data/
# No database/volume-backed state exists today — noted explicitly so restore
# doesn't go looking for something that was never there.
cat > "$backup_root/data/README.txt" <<'EOF'
No persistent data store exists outside ./audit and the caddy_data/caddy_config
Docker volumes (TLS certificate cache only, safely regenerated by Let's Encrypt
on the new host). Session state is in-memory by design (CLAUDE.md constraint
#4: "No stealth, no hidden install, no persistence"). Nothing to restore here.
EOF

# ---------------------------------------------------------------- docker/
{
  echo "# docker ps -a"
  sudo docker ps -a 2>&1 || docker ps -a 2>&1
  echo
  echo "# docker images"
  sudo docker images 2>&1 || docker images 2>&1
  echo
  echo "# docker volume ls"
  sudo docker volume ls 2>&1 || docker volume ls 2>&1
  echo
  echo "# docker network ls"
  sudo docker network ls 2>&1 || docker network ls 2>&1
} > "$backup_root/docker/docker-state.txt"

# Redacted compose config (drop anything env-substituted from a secret key).
docker compose --profile tls config 2>/dev/null \
  | grep -viE 'password|token|authtoken|secret' \
  > "$backup_root/docker/compose-config.redacted.yml" || true

# ---------------------------------------------------------------- system/
{
  echo "# os-release"; cat /etc/os-release 2>/dev/null
  echo; echo "# hostname"; hostname
  echo; echo "# uname -a"; uname -a
  echo; echo "# disk"; df -h /
  echo; echo "# memory"; free -h
  echo; echo "# docker --version"; docker --version 2>&1
  echo; echo "# docker compose version"; docker compose version 2>&1
  echo; echo "# listening ports (best-effort)"; (sudo ss -tlnp 2>&1 || ss -tlnp 2>&1)
  echo; echo "# systemd services (docker/caddy/duckdns, best-effort)"
  systemctl list-units --type=service --all 2>/dev/null | grep -iE 'docker|caddy|duckdns' || echo "(none found)"
  echo; echo "# crontab -l (best-effort)"; crontab -l 2>&1 || true
} > "$backup_root/system/system-info.txt"

# ---------------------------------------------------------------- manifests/
git_sha="$(git rev-parse HEAD)"
git_branch="$(git rev-parse --abbrev-ref HEAD)"
git_remote="$(git remote get-url origin 2>/dev/null || echo "(none)")"
git_dirty="clean"
git diff --quiet --ignore-submodules HEAD -- || git_dirty="DIRTY — uncommitted changes present"
public_host_present="NOT FOUND"
[[ -f .env ]] && grep -qE '^PUBLIC_HOST=' .env && public_host_present="FOUND"

cat > "$backup_root/manifests/MIGRATION_MANIFEST.md" <<EOF
# Migration Manifest — generated $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Source VM
- OS: $(. /etc/os-release; echo "$PRETTY_NAME")
- Kernel: $(uname -r)
- Hostname: $(hostname)
- Project directory: $repo_root

## Git
- Repository: $git_remote
- Branch: $git_branch
- Commit SHA: $git_sha
- Working tree: $git_dirty

## Docker
- Docker: $(docker --version 2>&1)
- Compose: $(docker compose version 2>&1 | head -1)
- Compose project: helpdeskanywhere
- Active profile observed at backup time: $(docker compose ps --status running --services 2>/dev/null | tr '\n' ',' | sed 's/,$//')

## Containers (expected)
- app        — server/Dockerfile, port 8080 internal only (expose, not published)
- caddy      — profile: tls   — publishes 80/443 (permanent DuckDNS path, PLAN 7.3)
- ngrok      — profile: ngrok — publishes 127.0.0.1:4040 only (temporary)
- cloudflared— profile: cloudflared — publishes 127.0.0.1:2000 only (temporary, no account/DNS)
Exactly one of caddy/ngrok/cloudflared should run at a time (one PUBLIC_HOST, one /ws Origin).

## Persistent volumes
- helpdeskanywhere_caddy_data, helpdeskanywhere_caddy_config — Let's Encrypt cert cache
  (tls profile only; safe to recreate empty on the new VM, Caddy re-issues automatically)
- ./audit (bind mount) — the only real persistent state; back this up, do not skip it

## Firewall / ports required
- 22/tcp  — SSH (administration)
- 80/tcp  — only for the tls profile (ACME HTTP-01 challenge + HSTS redirect)
- 443/tcp — only for the tls profile (HTTPS/WSS)
No inbound ports are required for the ngrok/cloudflared profiles — both dial out.

## Required environment variables (names only — see config/.env, restore manually)
$(sed -nE 's/^([A-Za-z_][A-Za-z0-9_]*)=.*/- \1/p' .env 2>/dev/null || echo "(.env not found)")

## Secrets present in .env (FOUND / NOT FOUND only)
- CONSOLE_PASSWORD: $(grep -qE '^CONSOLE_PASSWORD=.+' .env 2>/dev/null && echo FOUND || echo "NOT FOUND")
- NGROK_AUTHTOKEN:  $(grep -qE '^NGROK_AUTHTOKEN=.+' .env 2>/dev/null && echo FOUND || echo "NOT FOUND")
- PUBLIC_HOST set:  $public_host_present

## Domain / tunnel in use at backup time
See config/.env (PUBLIC_HOST) — not reproduced here as it identifies the live endpoint.
Cross-check against MIGRATION_DNS.md in the repo root for the cutover plan.

## systemd services required
None beyond docker.service itself. No DuckDNS renewal cron exists on this host
(Caddy's built-in ACME client handles renewal automatically when the tls profile
 is used — nothing to schedule separately).

## Required directories on the new VM
- <repo_root>/audit           (bind-mounted, must be writable by HOST_UID:HOST_GID)
- <repo_root>/server/public/download (applet .exe served from here)

## Application startup command
  cd <repo_root>
  export HOST_UID=\$(id -u) HOST_GID=\$(id -g)
  docker compose --profile <tls|ngrok|cloudflared> up -d --build

## Verification commands
  docker compose ps
  curl -fsS https://<host>/healthz
  ./scripts/verify-deployment.sh https://<host>
  ./scripts/cloud-migration/verify-migration.sh https://<host> $git_sha
EOF
echo "→ wrote manifests/MIGRATION_MANIFEST.md"

# ---------------------------------------------------------------- restore/
cat > "$backup_root/restore/README.txt" <<EOF
The restore script itself lives in the git repository (it is not duplicated
into this archive, so it can't drift from the code it restores):

  scripts/cloud-migration/restore-new-vm.sh

On the new VM: clone the repo at commit $git_sha, then run that script and
point it at this backup archive.
EOF

# ---------------------------------------------------------------- checksums
echo "→ computing checksums"
(
  cd "$backup_root"
  find config data audit generated docker system manifests restore -type f \
    ! -name 'SHA256SUMS' -print0 | sort -z | xargs -0 sha256sum > manifests/SHA256SUMS
)

# ---------------------------------------------------------------- archive
archive="$HOME/hda-migration-${timestamp}.tar.gz"
tar czf "$archive" -C "$backup_root" config data audit generated docker system manifests restore
sha256sum "$archive" > "${archive}.sha256"

archive_size="$(du -h "$archive" | cut -f1)"
echo
echo "────────────────────────────────────────────────────────────────────────"
echo "  Backup complete"
echo "  Staged:  $backup_root"
echo "  Archive: $archive ($archive_size)"
echo "  SHA256:  ${archive}.sha256"
echo "  Secrets: not printed to this console; .env copied with 600 permissions"
echo "────────────────────────────────────────────────────────────────────────"
